import type { Category, Transaction, User } from "./types";

export const mockUser: User = {
  name: "Conta teste",
  email: "conta@teste.com",
};

export const mockCategories: Category[] = [
  {
    id: "cat-alimentacao",
    name: "Alimentação",
    description: "Restaurantes, delivery e refeições",
    color: "blue",
    icon: "utensils",
  },
  {
    id: "cat-entretenimento",
    name: "Entretenimento",
    description: "Cinema, jogos e lazer",
    color: "pink",
    icon: "ticket",
  },
  {
    id: "cat-investimento",
    name: "Investimento",
    description: "Aplicações e retornos financeiros",
    color: "green",
    icon: "piggy-bank",
  },
  {
    id: "cat-mercado",
    name: "Mercado",
    description: "Compras de supermercado e mantimentos",
    color: "orange",
    icon: "shopping-cart",
  },
  {
    id: "cat-salario",
    name: "Salário",
    description: "Renda mensal e bonificações",
    color: "green",
    icon: "briefcase-business",
  },
  {
    id: "cat-saude",
    name: "Saúde",
    description: "Medicamentos, consultas e exames",
    color: "red",
    icon: "heart-pulse",
  },
  {
    id: "cat-transporte",
    name: "Transporte",
    description: "Gasolina, transporte público e viagens",
    color: "purple",
    icon: "car-front",
  },
  {
    id: "cat-utilidades",
    name: "Utilidades",
    description: "Energia, água, internet e telefone",
    color: "yellow",
    icon: "tool-case",
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "txn-01",
    description: "Cinema",
    date: "2025-12-18",
    amountInCents: 8800,
    type: "expense",
    categoryId: "cat-entretenimento",
  },
  {
    id: "txn-02",
    description: "Compras da Semana",
    date: "2025-12-15",
    amountInCents: 32045,
    type: "expense",
    categoryId: "cat-mercado",
  },
  {
    id: "txn-03",
    description: "Conta de Energia",
    date: "2025-12-12",
    amountInCents: 25200,
    type: "expense",
    categoryId: "cat-utilidades",
  },
  {
    id: "txn-04",
    description: "Posto de Gasolina",
    date: "2025-12-10",
    amountInCents: 18000,
    type: "expense",
    categoryId: "cat-transporte",
  },
  {
    id: "txn-05",
    description: "Jantar Delivery",
    date: "2025-12-08",
    amountInCents: 9500,
    type: "expense",
    categoryId: "cat-alimentacao",
  },
  {
    id: "txn-06",
    description: "Uber para o Aeroporto",
    date: "2025-12-06",
    amountInCents: 22000,
    type: "expense",
    categoryId: "cat-transporte",
  },
  {
    id: "txn-07",
    description: "Padaria",
    date: "2025-12-04",
    amountInCents: 4000,
    type: "expense",
    categoryId: "cat-alimentacao",
  },
  {
    id: "txn-08",
    description: "Compras de Natal",
    date: "2025-12-02",
    amountInCents: 98500,
    type: "expense",
    categoryId: "cat-mercado",
  },
  {
    id: "txn-09",
    description: "Pagamento de Salário",
    date: "2025-12-01",
    amountInCents: 425000,
    type: "income",
    categoryId: "cat-salario",
  },
  {
    id: "txn-10",
    description: "Jantar no Restaurante",
    date: "2025-11-30",
    amountInCents: 8950,
    type: "expense",
    categoryId: "cat-alimentacao",
  },
  {
    id: "txn-11",
    description: "Posto de Gasolina",
    date: "2025-11-29",
    amountInCents: 10000,
    type: "expense",
    categoryId: "cat-transporte",
  },
  {
    id: "txn-12",
    description: "Compras no Mercado",
    date: "2025-11-28",
    amountInCents: 15680,
    type: "expense",
    categoryId: "cat-mercado",
  },
  {
    id: "txn-13",
    description: "Retorno de Investimento",
    date: "2025-11-26",
    amountInCents: 34025,
    type: "income",
    categoryId: "cat-investimento",
  },
  {
    id: "txn-14",
    description: "Aluguel",
    date: "2025-11-26",
    amountInCents: 170000,
    type: "expense",
    categoryId: "cat-utilidades",
  },
  {
    id: "txn-15",
    description: "Freelance",
    date: "2025-11-24",
    amountInCents: 250000,
    type: "income",
    categoryId: "cat-salario",
  },
  {
    id: "txn-16",
    description: "Compras Jantar",
    date: "2025-11-22",
    amountInCents: 15000,
    type: "expense",
    categoryId: "cat-mercado",
  },
  {
    id: "txn-17",
    description: "Almoço Executivo",
    date: "2025-11-20",
    amountInCents: 6590,
    type: "expense",
    categoryId: "cat-alimentacao",
  },
  {
    id: "txn-18",
    description: "Conta de Internet",
    date: "2025-11-15",
    amountInCents: 12990,
    type: "expense",
    categoryId: "cat-utilidades",
  },
  {
    id: "txn-19",
    description: "Pizza em Família",
    date: "2025-11-12",
    amountInCents: 7850,
    type: "expense",
    categoryId: "cat-alimentacao",
  },
  {
    id: "txn-20",
    description: "Corrida de Aplicativo",
    date: "2025-11-08",
    amountInCents: 3275,
    type: "expense",
    categoryId: "cat-transporte",
  },
  {
    id: "txn-21",
    description: "Pagamento de Salário",
    date: "2025-11-01",
    amountInCents: 425000,
    type: "income",
    categoryId: "cat-salario",
  },
  {
    id: "txn-22",
    description: "Show de Rock",
    date: "2025-10-28",
    amountInCents: 14000,
    type: "expense",
    categoryId: "cat-entretenimento",
  },
  {
    id: "txn-23",
    description: "Dividendos",
    date: "2025-10-20",
    amountInCents: 242587,
    type: "income",
    categoryId: "cat-investimento",
  },
  {
    id: "txn-24",
    description: "Ingressos de Teatro",
    date: "2025-10-15",
    amountInCents: 9000,
    type: "expense",
    categoryId: "cat-entretenimento",
  },
  {
    id: "txn-25",
    description: "Corrida de Táxi",
    date: "2025-10-10",
    amountInCents: 4500,
    type: "expense",
    categoryId: "cat-transporte",
  },
  {
    id: "txn-26",
    description: "Restaurante Japonês",
    date: "2025-10-07",
    amountInCents: 21000,
    type: "expense",
    categoryId: "cat-alimentacao",
  },
  {
    id: "txn-27",
    description: "Pagamento de Salário",
    date: "2025-10-01",
    amountInCents: 425000,
    type: "income",
    categoryId: "cat-salario",
  },
];
